export const Fonts = {
    montserrat_Black: 'Montserrat-Black',
    montserrat_BlackItalic: 'Montserrat-BlackItalic',
    montserrat_Bold: 'Montserrat-Bold',
    montserrat_BoldItalic: 'Montserrat-BoldItalic',
    montserrat_ExtraBold: 'Montserrat-ExtraBold',
    montserrat_ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    montserrat_ExtraLight: 'Montserrat-ExtraLight',
    montserrat_ExtraLightItalic: 'Montserrat-ExtraLightItalic',
    montserrat_Italic: 'Montserrat-Italic',
    montserrat_Light: 'Montserrat-Light',
    montserrat_LightItalic: 'Montserrat-LightItalic',
    montserrat_Medium: 'Montserrat-Medium',
    montserrat_MediumItalic: 'Montserrat-MediumItalic',
    montserrat_Regular: 'Montserrat-Regular',
    montserrat_SemiBold: 'Montserrat-SemiBold',
    montserrat_SemiBoldItalic: 'Montserrat-SemiBoldItalic',
    montserrat_Thin: 'Montserrat-Thin',
    montserrat_ThinItalic: 'Montserrat-ThinItalic',
}